variable "system_name" {}
variable "environment" {}
variable "cidr_vpc" {}
variable "cidr_public1" {}
variable "cidr_public2" {}
variable "cidr_private1" {}
variable "cidr_private2" {}
variable "az_public1" {}
variable "az_public2" {}
variable "az_private1" {}
variable "az_private2" {}